### ISSUE TITLE
Couldn't work with Hexo 2.7.1

### ISSUE THREAD

**Issue by yangj1e** [someus/huno#1]
I try to use this theme with Hexo 2.7.1, but there is an error. Do you know how to resolve it?

```
TypeError: /Users/yangjie/Developer/blog/themes/huno/layout/layout.ejs:7
   5|     <meta http-equiv="X-UA-Compatible" content="chrome=1">
   6| 
>> 7|     <%
   8|     var title = page.title;
   9|     var description = page.description || '';
   10| 

Cannot call method 'substring' of null
   at eval (eval at <anonymous> (/Users/yangjie/Developer/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:65:31)
   at eval (eval at <anonymous> (/Users/yangjie/Developer/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:66:4294)
   at /Users/yangjie/Developer/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
   at Object.exports.render (/Users/yangjie/Developer/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
   at /Users/yangjie/Developer/blog/node_modules/hexo-renderer-ejs/index.js:5:14
   at store.(anonymous function) (/usr/local/lib/node_modules/hexo/lib/extend/renderer.js:67:27)
   at /usr/local/lib/node_modules/hexo/lib/core/render.js:96:9
   at fn (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:641:34)
   at Object._onImmediate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:557:34)
   at processImmediate [as _immediateCallback] (timers.js:336:15)
```

**Comment by shuixingjun** [comment]
hi,I don't need Github link in my index ,but i can't edit it. what should i do?
