### ISSUE TITLE
received an unhandled rejection TypeError after update to "hexo": "^3.1.0"

### ISSUE THREAD

**Issue by PokimLee** [someus/huno#5]
Unhandled rejection TypeError: /Users/pokim/Project/hexoFolder/themes/huno/layout/layout.ejs:6
    4|     <meta charset="utf-8">
    5|     <meta http-equiv="X-UA-Compatible" content="chrome=1">
    6|     <%
    7|     var title = page.title;
    8|     var description = page.description || '';
    9| 

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/pokim/Project/hexoFolder/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:66:30)
    at eval (eval at <anonymous> (/Users/pokim/Project/hexoFolder/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:67:4294)
    at /Users/pokim/Project/hexoFolder/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/pokim/Project/hexoFolder/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/Users/pokim/Project/hexoFolder/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Hexo.tryCatcher (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/pokim/Project/hexoFolder/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/pokim/Project/hexoFolder/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by someus** [comment]
`title` or `description` may not have been defined in hexo's config file.

**Comment by PokimLee** [comment]
@someus problem solved! thx
